<?php

namespace App\Services\Agent;

use App\Models\AgentRun;
use App\Models\ApprovalRequest;
use App\Models\PurchaseOrder;
use App\Models\User;
use Illuminate\Support\Facades\DB;

class PurchaseOrderDraftService
{
    /**
     * @param  array<int, array<string, mixed>>  $restockPlan
     * @param  array<string, mixed>|null  $recommendedSupplier
     */
    public function create(User $user, AgentRun $agentRun, array $restockPlan, ?array $recommendedSupplier, string $reasoning): ?PurchaseOrder
    {
        if ($restockPlan === [] || ! $recommendedSupplier) {
            return null;
        }

        return DB::transaction(function () use ($user, $agentRun, $restockPlan, $recommendedSupplier, $reasoning): PurchaseOrder {
            $items = collect($restockPlan)
                ->map(function (array $plan): array {
                    $quantity = (float) $plan['recommended_quantity'];
                    $unitPrice = (float) ($plan['estimated_unit_price'] ?? 0);

                    return [
                        'ingredient_id' => $plan['ingredient_id'],
                        'description' => $plan['ingredient_name'],
                        'quantity' => $quantity,
                        'unit' => $plan['unit'],
                        'unit_price' => $unitPrice,
                        'line_total' => round($quantity * $unitPrice, 2),
                    ];
                })
                ->values();

            $purchaseOrder = PurchaseOrder::create([
                'po_number' => $this->nextPoNumber(),
                'supplier_id' => $recommendedSupplier['id'],
                'agent_run_id' => $agentRun->id,
                'status' => PurchaseOrder::STATUS_PENDING_APPROVAL,
                'order_date' => now()->toDateString(),
                'subtotal' => $items->sum('line_total'),
                'notes' => 'Generated by TingHao Agent. Awaiting admin approval.',
                'agent_reasoning' => $reasoning,
                'email_to' => $recommendedSupplier['email'] ?? null,
                'created_by' => $user->id,
                'requested_by' => $user->id,
            ]);

            $purchaseOrder->items()->createMany($items->all());

            $purchaseOrder->approvalRequest()->create([
                'agent_run_id' => $agentRun->id,
                'type' => ApprovalRequest::TYPE_PURCHASE_ORDER,
                'status' => ApprovalRequest::STATUS_PENDING,
                'requested_by' => $user->id,
            ]);

            return $purchaseOrder->load(['supplier', 'items.ingredient', 'approvalRequest']);
        });
    }

    private function nextPoNumber(): string
    {
        $year = now()->format('Y');
        $count = PurchaseOrder::where('po_number', 'like', "PO-{$year}-%")->count() + 1;

        return sprintf('PO-%s-%04d', $year, $count);
    }
}
