@extends('layouts.app')

@section('content')
<main class="admin-page agent-console-page">
    <section class="page-shell">
        <div class="page-heading">
            <div>
                <p class="eyebrow">Track 4 Autopilot Agent</p>
                <h1>Expiry Loss Prevention</h1>
                <p>This recommendation is generated by TingHao Agent to reduce waste before ingredients expire.</p>
            </div>
            <div class="page-actions">
                <a href="{{ route('agent.index') }}" class="btn btn-muted">Agent Audit</a>
                <a href="{{ route('expiry.index') }}" class="btn btn-muted">Expiry Tracking</a>
                @if (auth()->user()->isAdmin())
                    <form method="post" action="{{ route('agent.expiry-loss.scan') }}">
                        @csrf
                        <button type="submit" class="btn btn-primary">Run Expiry Loss Scan</button>
                    </form>
                @endif
            </div>
        </div>

        @if (session('status'))
            <div class="success-alert">{{ session('status') }}</div>
        @endif

        <section class="expiry-impact-grid">
            <article class="info-panel expiry-impact-card">
                <p class="eyebrow">Potential RM at risk this week</p>
                <h2>RM {{ number_format($summary['total_potential_loss'], 2) }}</h2>
                <p>{{ $summary['at_risk_count'] }} ingredient(s) with open recommendations.</p>
            </article>
            <article class="info-panel expiry-impact-card">
                <p class="eyebrow">Highest-risk ingredient</p>
                <h2>{{ $summary['highest_risk_name'] ?? 'No active risk' }}</h2>
                <p>{{ $summary['highest_risk_loss'] !== null ? 'RM '.number_format($summary['highest_risk_loss'], 2).' at risk' : 'Run a scan to calculate current RM exposure.' }}</p>
            </article>
            <article class="info-panel expiry-impact-card">
                <p class="eyebrow">Latest scan</p>
                <h2>{{ $latestScan?->created_at?->format('d M Y, H:i') ?? 'Not run yet' }}</h2>
                @if ($latestScan)
                    <p><a href="{{ route('agent.runs.show', $latestScan) }}">Open tool call timeline</a></p>
                @else
                    <p>Admin can run the first expiry loss scan from this page.</p>
                @endif
            </article>
        </section>

        <section class="table-card">
            <div class="agent-card-heading compact">
                <div>
                    <p class="eyebrow">Open recommendations</p>
                    <h2>Expiry Loss Prevention</h2>
                </div>
            </div>
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Ingredient</th>
                        <th>Quantity at risk</th>
                        <th>Potential loss</th>
                        <th>Expiry</th>
                        <th>Recommendation</th>
                        <th>Status</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($recommendations as $recommendation)
                        <tr>
                            <td>
                                <strong>{{ $recommendation->ingredient?->name ?? 'Deleted ingredient' }}</strong>
                                <span>{{ $recommendation->ingredient?->sku ?? 'No SKU' }}</span>
                            </td>
                            <td>{{ number_format((float) $recommendation->quantity_at_risk, 2) }} {{ $recommendation->unit }}</td>
                            <td>{{ $recommendation->potential_loss !== null ? 'RM '.number_format((float) $recommendation->potential_loss, 2) : 'Cost unavailable' }}</td>
                            <td>
                                {{ $recommendation->expiry_date?->format('d M Y') ?? 'Not set' }}
                                <span>{{ $recommendation->days_until_expiry }} day(s)</span>
                            </td>
                            <td>
                                <strong>{{ $recommendation->recommendation_title }}</strong>
                                <span>{{ str($recommendation->recommendation_body)->limit(120) }}</span>
                            </td>
                            <td><span class="status-pill expiry-loss-status-{{ $recommendation->status }}">{{ ucfirst($recommendation->status) }}</span></td>
                            <td class="table-actions">
                                <a href="{{ route('expiry-loss-recommendations.show', $recommendation) }}">View</a>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="7" class="empty-state">No expiry loss recommendations yet.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </section>

        <div class="pagination-wrap">
            {{ $recommendations->links() }}
        </div>
    </section>
</main>
@endsection
