@extends('layouts.app')

@section('content')
<main class="admin-page agent-console-page">
    <section class="page-shell">
        <div class="page-heading">
            <div>
                <p class="eyebrow">Expiry Loss Recommendation</p>
                <h1>{{ $recommendation->recommendation_title }}</h1>
                <p>This recommendation is generated by TingHao Agent to reduce waste before ingredients expire.</p>
            </div>
            <div class="page-actions">
                <a href="{{ route('agent.expiry-loss') }}" class="btn btn-muted">Expiry Loss</a>
                <a href="{{ route('expiry.index') }}" class="btn btn-muted">Expiry Tracking</a>
            </div>
        </div>

        @if (session('status'))
            <div class="success-alert">{{ session('status') }}</div>
        @endif

        <section class="agent-result-grid">
            <article class="info-panel expiry-recommendation-card">
                <p class="eyebrow">Ingredient at risk</p>
                <h2>{{ $recommendation->ingredient?->name ?? 'Deleted ingredient' }}</h2>
                <div class="agent-meta-grid">
                    <div><span>Quantity</span><strong>{{ number_format((float) $recommendation->quantity_at_risk, 2) }} {{ $recommendation->unit }}</strong></div>
                    <div><span>Cost price</span><strong>{{ $recommendation->cost_price !== null ? 'RM '.number_format((float) $recommendation->cost_price, 2) : 'Unavailable' }}</strong></div>
                    <div><span>Potential loss</span><strong>{{ $recommendation->potential_loss !== null ? 'RM '.number_format((float) $recommendation->potential_loss, 2) : 'Cost unavailable' }}</strong></div>
                    <div><span>Expiry date</span><strong>{{ $recommendation->expiry_date?->format('d M Y') ?? 'Not set' }}</strong></div>
                    <div><span>Days until expiry</span><strong>{{ $recommendation->days_until_expiry }}</strong></div>
                    <div><span>Status</span><strong>{{ ucfirst($recommendation->status) }}</strong></div>
                </div>
            </article>

            <article class="info-panel expiry-recommendation-card">
                <p class="eyebrow">Qwen recommendation</p>
                <h2>{{ $recommendation->recommendation_title }}</h2>
                <p class="agent-summary">{{ $recommendation->recommendation_body }}</p>
                <p class="agent-summary">The agent does not recommend using expired ingredients and only scans stock that has not expired.</p>
            </article>
        </section>

        @if (auth()->user()->isAdmin())
            <section class="info-panel">
                <p class="eyebrow">Admin actions</p>
                <h2>Review status</h2>
                <div class="form-actions">
                    <form method="post" action="{{ route('expiry-loss-recommendations.review', $recommendation) }}">
                        @csrf
                        <button type="submit" class="btn btn-muted">Mark Reviewed</button>
                    </form>
                    <form method="post" action="{{ route('expiry-loss-recommendations.dismiss', $recommendation) }}">
                        @csrf
                        <button type="submit" class="btn btn-muted">Dismiss</button>
                    </form>
                    <form method="post" action="{{ route('expiry-loss-recommendations.complete', $recommendation) }}">
                        @csrf
                        <button type="submit" class="btn btn-primary">Mark Completed</button>
                    </form>
                </div>
                <p class="agent-summary">Reviewed by: {{ $recommendation->reviewedBy?->name ?? 'Not reviewed yet' }}</p>
            </section>
        @elseif (in_array($recommendation->status, [\App\Models\ExpiryLossRecommendation::STATUS_ACTIVE, \App\Models\ExpiryLossRecommendation::STATUS_REVIEWED], true))
            <section class="info-panel">
                <p class="eyebrow">Human checkpoint</p>
                <h2>Waiting for admin action</h2>
                <p class="agent-summary">An admin must review, dismiss, or complete this recommendation. The agent cannot complete expiry actions by itself.</p>
            </section>
        @endif

        @if ($recommendation->agentRun)
            <details class="info-panel advanced-details-panel">
                <summary>{{ __('messages.advanced_details') }}</summary>
                <div class="advanced-details-body">
            <x-agent.reasoning-activity :steps="$recommendation->agentRun->reasoningSteps" />

            <section class="info-panel">
                <p class="eyebrow">Agent audit</p>
                <h2>Tool call timeline</h2>
                <p><a href="{{ route('agent.runs.show', $recommendation->agentRun) }}">Open Agent Run #{{ $recommendation->agentRun->id }}</a></p>
                <div class="agent-timeline">
                    @foreach ($recommendation->agentRun->toolCalls as $toolCall)
                        <article>
                            <span>{{ $loop->iteration }}</span>
                            <div>
                                <strong>{{ $toolCall->tool_name }}</strong>
                                <em>{{ $toolCall->created_at->format('H:i:s') }} · {{ ucfirst($toolCall->status) }}</em>
                            </div>
                        </article>
                    @endforeach
                </div>
            </section>
                </div>
            </details>
        @endif
    </section>
</main>
@endsection
